version: '3.8'

services:
  postgres:
    image: postgres:14.5
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_USER:-dev_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  postgres-data: # named volumes can be managed easier using docker-compose
    driver: local